version: '2.1'
services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-api-localstack_main}"
    image: localstack/localstack-pro:latest
    network_mode: bridge
    ports:
      - "4566:4566"
      - "4571:4571"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
       - SERVICES=iot,sts,cloudformation,ecr,iam,ssm,lambda,dynamodb,cognito-idp,cloudfront,apigateway,cloudwatch
       - DEBUG=${DEBUG-}
       - DATA_DIR=${DATA_DIR-}
       - PORT_WEB_UI=${PORT_WEB_UI-}
       - LAMBDA_EXECUTOR=docker
       - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY-}
       - DOCKER_HOST=unix:///var/run/docker.sock
       - HOST_TMP_FOLDER=${TMPDIR}
       - DEFAULT_REGION=ap-northeast-1
       - IMAGE_NAME=localstack/localstack-full
       - LOCALSTACK_AUTH_TOKEN="ls-giYu7795-LiYA-fiDi-tedo-4269vIMEe4d1"
       - LS_LOG=trace
    volumes:
      - "${TMPDIR:-/tmp/localstack_}:/tmp/localstack_"
      - "/var/run/docker.sock:/var/run/docker.sock"